# Server config
server.port=8080

# Database config
spring.r2dbc.url=r2dbc:postgresql://postgres:5432/the-resume
spring.r2dbc.username=${SPRING_DATASOURCE_USERNAME}
spring.r2dbc.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always

# OpenAI API key (secure this properly in production!)
openai.api.key=${OPENAI_API_KEY}

# Path to the master prompt file
openai.master-prompt.file=classpath:master-prompt.txt
