# Server config
server.port=8080

# Database config
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

#JWT config
jwt.secret=${JWT_SECRET}
jwt.expiration=1800000
jwt.clock-skew-seconds=30

# OpenAI API key (secure this properly in production!)
openai.api.key=${OPENAI_API_KEY}

# Path to the master prompt file
openai.master-prompt.file=classpath:master-prompt.txt

# Logging configuration
logging.level.com.muryshkin.net.backend.chat=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# ReCaptcha configuration
recaptcha.secret.key=${RECAPTCHA_SECRET_KEY}

# Telegram Bot Token
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}